source 'https://rubygems.org'
gem 'bundler'
gem 'jekyll'
gem 'sanitize'
gem 'tire'
gem 'activesupport'
gem 'redcarpet'
gem 'capistrano', '~>3.0.0'
gem 'capistrano-bundler'
gem 'capistrano-rbenv', github: 'capistrano/rbenv'
